nome = input('Nome: ')
sobrenome = input('Sobrenome: ')
idade = input('Idade: ')
datanascimento = input('Data de nascimento: ')
maior = int(idade) > 18
altura = input('Altura: ')
print('Nome:', nome)
print('Sobrenome:', sobrenome)
print('Idade:', idade)
print('Data de mascimento:', datanascimento)
print('É maior de idade?', maior)
print('Altura:', altura)
